# Generated by Django 5.2.9 on 2025-12-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='batch_id',
            field=models.UUIDField(default='1d90a62a-1335-45a4-838c-b9834f15af05'),
            preserve_default=False,
        ),
    ]
