# Generated by Django 5.2.9 on 2025-12-09 05:19

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0002_transaction_batch_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('bi_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
