# Generated by Django 5.2.9 on 2025-12-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transact', '0003_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
    ]
